%YAML 1.2
---
# Main configuration document

llsfrb:
  plugins: ""

  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log

  clips:
    dir: "@BASEDIR@/rockin/clips"
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: []
    unwatch-rules: []

  comm:
    protobuf-dirs: ["@BASEDIR@/rockin/msgs"]

    server-port: !tcp-port 4444
    
    public-peer:
      host: !ipv4 137.226.233.255
      port: !udp-port 4444
      #send-port: !udp-port 4444
      #recv-port: !udp-port 4445

  mongodb:
    enable: true
    hostport: localhost
    collections:
      text-log: llsfrb.log
      clips-log: llsfrb.clipslog
      protobuf: llsfrb.protobuf

  game:
    teams: [RoCKInNRoLLIn]
    crypto-keys:
      RoCKInNRoLLIn: randomkey

  shell:
    refbox-host: localhost
    refbox-port: 4444