%YAML 1.2
---
# Main configuration document

llsfrb:
  plugins: "drilling_machine,conveyor_belt"

  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log
   
  conveyor-belt:
    enable: false
    host: !ipv4 192.168.1.101
    command_port: !tcp-port 55502
    status_port: !tcp-port 55501
    
  drilling-machine:
    enable: false
    host: !ipv4 192.168.1.103
    command_port: !tcp-port 55512
    status_port: !tcp-port 55511

  clips:
    dir: "@BASEDIR@/rockin/clips"
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time]
    unwatch-rules: [retract-time]

  comm:
    protobuf-dirs: ["@BASEDIR@/rockin/msgs"]

    server-port: !tcp-port 4444
    
    public-peer:
      host: !ipv4 137.226.233.255
      port: !udp-port 4444
      #send-port: !udp-port 4444
      #recv-port: !udp-port 4445

    RoCKInNRoLLIn-peer:
      host: !ipv4 127.0.0.1
      port: !udp-port 4446
      #send-port: !udp-port 4446
      #recv-port: !udp-port 4447

  mongodb:
    enable: true
    hostport: localhost
    collections:
      text-log: llsfrb.log
      clips-log: llsfrb.clipslog
      protobuf: llsfrb.protobuf

  game:
    teams: [RoCKInNRoLLIn]
    crypto-keys:
      RoCKInNRoLLIn: randomkey

  shell:
    refbox-host: localhost
    refbox-port: 4444